### ISSUE TITLE
Change logo on New site

### ISSUE THREAD

**Issue by ben-bishop** [CarbonLDP/carbonldp-website#239] opened 2018-02-28 14:59 UTC
Update the logo on the site.
[CarbonLDP Logo 2018.zip](https://github.com/CarbonLDP/carbonldp-website/files/1767532/CarbonLDP.Logo.2018.zip)

**Comment by alvaro9210** [comment] 2018-02-28 17:37
Closing because of dupe of #237 - Change logo

**Closed by alvaro9210** 2018-02-28 17:37 UTC
Labels: priority2: required, type: task
