### ISSUE TITLE
Create visual documentation for the Workbench

### ISSUE THREAD

**Issue by codyburleson** [CarbonLDP/carbonldp-website#205] opened 2018-01-30 18:27 UTC
We need a high-level and visual document in the website about the Workbench:

- what it is
- what are it's main screens and features

As an initial document, this does not have to go into finite details about how to use ("click here, do this, click here"). But, there needs to be a stronger affirmation that the Workbench exists, what it does, what it looks like, etc.

**Comment by MiguelAraCo** [comment] 2018-01-31 16:21
Duplicate of #180

**Closed by MiguelAraCo** 2018-01-31 16:21 UTC
Labels: priority3: nice-to-have, type: suggestion
